### ISSUE TITLE
User Story Development

### ISSUE THREAD

**Issue by Samiabutton** [button-inc/emissions-elt-demo#145]
Acceptance Criteria:

```[tasklist]
### Tasks
- [ ] Create user stories based on personas.
- [ ] Share user stories with the rest of the ClimateTrax team.
- [ ] Upload user stories into Sharepoint (Sprint 3 folder)
```
