### ISSUE TITLE
refactor: DAG refinement

### ISSUE THREAD

**Issue by joshgamache** [button-inc/emissions-elt-demo#202]
```[tasklist]
### Tasks
- [ ] A few of the current DAGs have a run-order dependence. It would be good practice to combine these into a single DAG for flow handling 
- [ ] DAGs, as they are, currently only load initial data but not subsequent data. A separate _initial load_ DAG should exists, which is then supported by triggered/scheduled DAGs to ingest new data.

- [ ] DAGs are triggered manually. A DAG should be created to monitor the storage dropbox and send to the correct pipeline.
```
