### ISSUE TITLE
Create the page header & layout

### ISSUE THREAD

**Issue by mikevespi** [button-inc/emissions-elt-demo#87]
We need a header component and a default layout component for the app. This should be done using the Button component library, in the Button theme (as much as possible). 

Mocks: https://www.figma.com/file/xOtnhSwtw6foL6Br5a8yjQ/ELT-Demo

At the time of writing this, the layout only contains the header, and the page content (to be passed down as children). The mocks are subject to change in the immediate future so be sure to reference them and sync up with the design team before you start!

You can look at the `DefaultLayout.tsx` in the [CAS repo](https://github.com/bcgov/cas-cif/tree/develop/app/components/Layout) for inspiration. If you do, we can ignore the session related code until we have auth set up.

### Tasks (How)
- [ ] Create a `DefaultLayout` component containing the page header, and the children passed in, matching the mocks
- [ ] Create a header component
- [ ] Tests for the components
